package com.flightsearch.backend.models;

public enum TravelerPricingFareOption {
    STANDARD,
    INCLUSIVE_TOUR,
    SPANISH_MELILLA_RESIDENT,
    SPANISH_CEUTA_RESIDENT,
    SPANISH_CANARY_RESIDENT,
    SPANISH_BALEARIC_RESIDENT,
    AIR_FRANCE_METROPOLITAN_DISCOUNT_PASS,
    AIR_FRANCE_DOM_DISCOUNT_PASS,
    AIR_FRANCE_COMBINED_DISCOUNT_PASS,
    AIR_FRANCE_FAMILY,
    ADULT_WITH_COMPANION,
    COMPANION
}
